# Generated by Django 5.2.8 on 2025-11-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer', models.CharField(max_length=255)),
                ('DispatchTo', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('LocalCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('ParPallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('UOM', models.CharField(blank=True, max_length=50, null=True)),
                ('PacInCtn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('DispatchID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNo', models.CharField(max_length=100, unique=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('OrderDate', models.DateField()),
                ('LoadingDate', models.DateField(blank=True, null=True)),
                ('DeliveryDate', models.DateField(blank=True, null=True)),
                ('TransportNo', models.CharField(blank=True, max_length=100, null=True)),
                ('DriverName', models.CharField(blank=True, max_length=255, null=True)),
                ('DriverMobile', models.CharField(blank=True, max_length=50, null=True)),
                ('Seal', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispatch_app.customer')),
            ],
            options={
                'db_table': 'Dispatch',
            },
        ),
        migrations.CreateModel(
            name='DispatchDetails',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LocalCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('UOM', models.CharField(blank=True, max_length=50, null=True)),
                ('PackInCarton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('ParPallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DispatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dispatch_app.dispatch')),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispatch_app.products')),
            ],
            options={
                'db_table': 'DispatchDetails',
            },
        ),
    ]
