# Generated by Django 5.2.8 on 2025-11-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdetails',
            name='ExpairyDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchdetails',
            name='ProductionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
